import type { Metadata } from "next"
import { Clock, Dumbbell, Filter, Plus, Search } from "lucide-react"

import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { WorkoutGeneratorForm } from "@/components/workout-generator-form"

export const metadata: Metadata = {
  title: "Workouts - FitAI",
  description: "Personalized workout plans generated by AI",
}

export default function WorkoutsPage() {
  return (
    <div className="flex min-h-screen flex-col">
      <div className="flex-1 space-y-4 p-4 md:p-8 pt-6">
        <div className="flex items-center justify-between space-y-2">
          <h2 className="text-3xl font-bold tracking-tight">Workouts</h2>
          <div className="flex items-center space-x-2">
            <Button>
              <Plus className="mr-2 h-4 w-4" />
              Generate New Workout
            </Button>
          </div>
        </div>
        <Tabs defaultValue="my-workouts" className="space-y-4">
          <TabsList>
            <TabsTrigger value="my-workouts">My Workouts</TabsTrigger>
            <TabsTrigger value="generator">Workout Generator</TabsTrigger>
            <TabsTrigger value="history">History</TabsTrigger>
          </TabsList>
          <TabsContent value="my-workouts" className="space-y-4">
            <div className="flex items-center justify-between">
              <div className="relative w-full max-w-sm">
                <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
                <Input
                  type="search"
                  placeholder="Search workouts..."
                  className="w-full bg-background pl-8 md:w-[300px]"
                />
              </div>
              <Button variant="outline" size="sm">
                <Filter className="mr-2 h-4 w-4" />
                Filter
              </Button>
            </div>
            <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
              <Card>
                <CardHeader>
                  <CardTitle>Upper Body Strength</CardTitle>
                  <CardDescription>Focus on chest, shoulders, and arms</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="flex items-center space-x-4 text-sm text-muted-foreground">
                    <div className="flex items-center">
                      <Dumbbell className="mr-1 h-4 w-4" />
                      <span>Intermediate</span>
                    </div>
                    <div className="flex items-center">
                      <Clock className="mr-1 h-4 w-4" />
                      <span>45 min</span>
                    </div>
                  </div>
                  <div className="mt-4 space-y-2">
                    <div className="flex justify-between text-sm">
                      <span>Bench Press</span>
                      <span>3 sets x 10 reps</span>
                    </div>
                    <div className="flex justify-between text-sm">
                      <span>Shoulder Press</span>
                      <span>3 sets x 12 reps</span>
                    </div>
                    <div className="flex justify-between text-sm">
                      <span>Tricep Extensions</span>
                      <span>3 sets x 15 reps</span>
                    </div>
                    <div className="flex justify-between text-sm">
                      <span>Bicep Curls</span>
                      <span>3 sets x 12 reps</span>
                    </div>
                  </div>
                </CardContent>
                <CardFooter>
                  <Button className="w-full">Start Workout</Button>
                </CardFooter>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Lower Body Power</CardTitle>
                  <CardDescription>Focus on legs and glutes</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="flex items-center space-x-4 text-sm text-muted-foreground">
                    <div className="flex items-center">
                      <Dumbbell className="mr-1 h-4 w-4" />
                      <span>Advanced</span>
                    </div>
                    <div className="flex items-center">
                      <Clock className="mr-1 h-4 w-4" />
                      <span>50 min</span>
                    </div>
                  </div>
                  <div className="mt-4 space-y-2">
                    <div className="flex justify-between text-sm">
                      <span>Squats</span>
                      <span>4 sets x 8 reps</span>
                    </div>
                    <div className="flex justify-between text-sm">
                      <span>Deadlifts</span>
                      <span>4 sets x 6 reps</span>
                    </div>
                    <div className="flex justify-between text-sm">
                      <span>Lunges</span>
                      <span>3 sets x 12 reps</span>
                    </div>
                    <div className="flex justify-between text-sm">
                      <span>Calf Raises</span>
                      <span>3 sets x 15 reps</span>
                    </div>
                  </div>
                </CardContent>
                <CardFooter>
                  <Button className="w-full">Start Workout</Button>
                </CardFooter>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>HIIT Cardio</CardTitle>
                  <CardDescription>High-intensity interval training</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="flex items-center space-x-4 text-sm text-muted-foreground">
                    <div className="flex items-center">
                      <Dumbbell className="mr-1 h-4 w-4" />
                      <span>All Levels</span>
                    </div>
                    <div className="flex items-center">
                      <Clock className="mr-1 h-4 w-4" />
                      <span>30 min</span>
                    </div>
                  </div>
                  <div className="mt-4 space-y-2">
                    <div className="flex justify-between text-sm">
                      <span>Jumping Jacks</span>
                      <span>45 sec</span>
                    </div>
                    <div className="flex justify-between text-sm">
                      <span>Mountain Climbers</span>
                      <span>45 sec</span>
                    </div>
                    <div className="flex justify-between text-sm">
                      <span>Burpees</span>
                      <span>45 sec</span>
                    </div>
                    <div className="flex justify-between text-sm">
                      <span>Rest</span>
                      <span>15 sec between exercises</span>
                    </div>
                  </div>
                </CardContent>
                <CardFooter>
                  <Button className="w-full">Start Workout</Button>
                </CardFooter>
              </Card>
            </div>
          </TabsContent>
          <TabsContent value="generator" className="space-y-4">
            <WorkoutGeneratorForm />
          </TabsContent>
          <TabsContent value="history" className="space-y-4">
            <div className="rounded-md border">
              <div className="p-4">
                <h3 className="text-lg font-medium">Workout History</h3>
                <p className="text-sm text-muted-foreground">View your past workouts and track your progress</p>
              </div>
              <div className="p-4">
                <div className="space-y-4">
                  <div className="flex items-center justify-between border-b pb-4">
                    <div>
                      <h4 className="font-medium">Upper Body Strength</h4>
                      <p className="text-sm text-muted-foreground">April 5, 2025</p>
                    </div>
                    <Button variant="outline" size="sm">
                      View Details
                    </Button>
                  </div>
                  <div className="flex items-center justify-between border-b pb-4">
                    <div>
                      <h4 className="font-medium">HIIT Cardio</h4>
                      <p className="text-sm text-muted-foreground">April 4, 2025</p>
                    </div>
                    <Button variant="outline" size="sm">
                      View Details
                    </Button>
                  </div>
                  <div className="flex items-center justify-between border-b pb-4">
                    <div>
                      <h4 className="font-medium">Lower Body Power</h4>
                      <p className="text-sm text-muted-foreground">April 3, 2025</p>
                    </div>
                    <Button variant="outline" size="sm">
                      View Details
                    </Button>
                  </div>
                  <div className="flex items-center justify-between border-b pb-4">
                    <div>
                      <h4 className="font-medium">Core Strength</h4>
                      <p className="text-sm text-muted-foreground">April 2, 2025</p>
                    </div>
                    <Button variant="outline" size="sm">
                      View Details
                    </Button>
                  </div>
                  <div className="flex items-center justify-between">
                    <div>
                      <h4 className="font-medium">Upper Body Strength</h4>
                      <p className="text-sm text-muted-foreground">April 1, 2025</p>
                    </div>
                    <Button variant="outline" size="sm">
                      View Details
                    </Button>
                  </div>
                </div>
              </div>
            </div>
          </TabsContent>
        </Tabs>
      </div>
    </div>
  )
}

